### ISSUE TITLE
Update at_talk to not use sync at all

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_talk#6]
There is no need for sync as at_talk now uses notifications

- [x] Remove sync
- [ ] If sending a file then do not prepend the atSign in the UI
- [ ] Stretch deal with multi users and screen handling using Tim Sneath's https://pub.dev/packages/dart_console

**Comment by cconstab** [comment]
Sync removed but highlighted bug that needs solving first.. The first sent message gets "lost" this may be due to the public keys not being available yet but needs investigating and raising a bug..

**Comment by cconstab** [comment]
The above needs documenting into a bug if confirmed with @gkc & @murali-shris

**Comment by gkc** [comment]
@cconstab Is this complete?

**Comment by cconstab** [comment]
completed without stretch goals which I will migrate to enhancements
